# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/i3blocks/scripts/$BLOCK_NAME/$BLOCK_NAME
separator=true
separator_block_width=10

[disk_usage]
label= 
interval=30

[temperature]
label= 
interval=10
T_WARN=70
T_CRIT=90

[load_average]
label= 
interval=10

[volume-pipewire]
interval=once
signal=1

# [time]
# label= 
# command=date '+%Y-%m-%d %H:%M:%S'
# interval=1

[calendar]
interval=1
LABEL= 
